AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  egrid-aws-lambda

  Sample SAM Template for egrid-aws-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  EGridSubRegionsReaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: egrid-subregions-reader/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Policies:
        - S3ReadPolicy:  # Custom policy name (can be anything meaningful)
            BucketName: egrid-subregions-cloudcafe
      Events:
        EGridSubRegionsReader:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /egrid_subregions
            Method: post

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EGridSubRegionsReaderApi:
    Description: API Gateway endpoint URL for Prod egrid_subregions
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/egrid_subregions/"
  EGridSubRegionsReaderFunction:
    Description: eGrid Reader Function ARN
    Value: !GetAtt EGridSubRegionsReaderFunction.Arn
  EGridSubRegionsReaderFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt EGridSubRegionsReaderFunction.Arn
